version: '3.8'

services:
  backend:
    image: somke01/kolector-backend:latest
    container_name: kolector-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Replace with environment variable names from Jenkins
      - DJANGO_SETTINGS_MODULE=kolector.settings.prod
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8000", "kolector.wsgi:application"]
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  static_volume:
  media_volume:
  db_data: