version: '3.8'

services:
  backend:
    image: somke01/kolector-backend:latest
    container_name: kolector-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: kolector.settings.prod
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db-name}
      POSTGRES_USER: ${POSTGRES_USER:-db-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-db-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume:
  media_volume:
  db_data:
